
[tools]
task = '3.36.0'
kubectl = '1.29.4'
fzf = '0.44.0'
yq = '4.40.1'
jq = '1.7'
k3d = '5.5.1'
pre-commit = "3.7.0"
yamllint = "1.35.1"
helmfile = "0.165.0"
helm = "3.15.2"
go = '1.22.2'
#"go:github.com/helm/chart-releaser" = "1.6.1"

