{{- $root := . -}}
{{- $common := dict "Values" .Values.common -}}
{{- $noCommon := omit .Values "common" -}}
{{- $overrides := dict "Values" $noCommon -}}
{{- $noValues := omit . "Values" -}}
{{- with merge $noValues $overrides $common -}}

{{- $cert := .Values.certificate -}}
{{- if $cert.enabled }}
apiVersion: cert-manager.io/v1alpha2
kind: {{ $cert.kind | default "Certificate" }}
metadata:
  name: {{ $cert.name }}
spec:
{{- if $cert.selfSigned }}
  issuerRef:
    name: {{ $cert.issuer | default "cert-manager/default" }}
    kind: Issuer
{{- else }}
  issuerRef:
    name: {{ $cert.issuer | default "cert-manager/letsencrypt-staging" }}
    kind: ClusterIssuer
{{- end }}
  secretName: {{ $cert.name }}
  commonName: {{ $cert.commonName | quote }}
  isCA: {{ $cert.isCA }}
  dnsNames:
    - {{ $cert.commonName | quote }}
{{- with $cert.dnsNames }}
{{ . | indent 8 }}
{{- end }}
{{- end }}
{{- end -}}