{{- $root := . -}}
{{- $common := dict "Values" .Values.common -}}
{{- $noCommon := omit .Values "common" -}}
{{- $overrides := dict "Values" $noCommon -}}
{{- $noValues := omit . "Values" -}}

{{- with merge $noValues $overrides $common -}}
{{- $config := .Values.clusterRoleBinding -}}

{{- if $config.enabled }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ $config.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $config.roleName }}
subjects:
- kind: ServiceAccount
  name: {{ $config.serviceAccountName }}
  namespace: {{ $config.serviceAccountNamespace }}
{{- end }}

{{- end -}}