{{- $root := . -}}
{{- $common := dict "Values" .Values.common -}}
{{- $noCommon := omit .Values "common" -}}
{{- $overrides := dict "Values" $noCommon -}}
{{- $noValues := omit . "Values" -}}

{{- with merge $noValues $overrides $common -}}
{{- $config := .Values.clusterRole -}}

{{- if $config.enabled }}
## ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ $config.name }}
rules:
{{- if $config.rules }}
{{- with $config.rules }}
{{ toYaml . | indent 2 }}
{{- end }}
{{- else }}
- apiGroups: [""]
  resources:
  - nodes
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["get"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
{{- end }}

{{- end }}

{{- end -}}
