{{- $root := . -}}
{{- $dockercfg := .Values.dockercfg -}}
{{- if $dockercfg.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "archetype.fullname" . }}-dockercfg
  labels:
    {{- include "common.labels" $root | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "archetype.imagePullSecret" $root }}
{{- end -}}
