{{- $root := . -}}
{{- $common := dict "Values" .Values.common -}}
{{- $noCommon := omit .Values "common" -}}
{{- $overrides := dict "Values" $noCommon -}}
{{- $noValues := omit . "Values" -}}
{{- with merge $noValues $overrides $common -}}
{{- $config := .Values.ingress -}}

{{- if and $config.enabled ( eq $config.type "standard" ) }}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ include "archetype.shortname" $root }}
  annotations:
{{- if hasKey $config "annotations" }}
    {{- with $config.annotations }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
{{- include "archetype.ingress.class" $root | nindent 4 }}
{{- include "archetype.certissuer" (list .Values.certIssuerMap .Values.zone) | nindent 4 }}
{{- if $config.forecastle }}
    forecastle.stakater.com/expose: {{ .Values.ingress.forecastle | quote }}
{{- end }}
    service.beta.kubernetes.io/{{ .Values.cloud | default "local" }}-load-balancer-internal: "true"
{{- if $config.prometheusScraped }}
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ $config.prometheusPort | default .Values.ports.prometheus | quote }}
{{- end }}
{{- if $config.enableSSLRedirect }}
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
{{- end }}
{{- if $config.rewrite }}
    ingress.kubernetes.io/rewrite-target: {{ $config.rewriteTarget | default "/" | quote }}
{{- end }}
  labels:
    ingressName: {{ include "archetype.shortname" $root }}
    dnsRoot: {{ .Values.dnsRoot }}
    {{- include "archetype.labels" $root | nindent 4 }}
{{- with $config.labels }}
    {{ toYaml . | nindent 4 }}
{{- end }}
spec:
  rules:
{{- range $host := $config.hosts }}
{{- if $host.name }}
    - host: {{ $host.name | quote }}
{{- else }}
    - host: "{{ include "archetype.appname" $root }}.{{ include "archetype.clusterdns" $root }}"
{{- end -}}
{{- if $host.config }}
{{- $host.config | toYaml | nindent 6 }}
{{- else }}
{{- include "archetype.ingress.service" $root | nindent 6 }}
{{- end }}
{{- if or $config.tlsEnabled $host.secretName }}
  tls:
    - hosts:
{{- if $host.name }}
      - {{ $host.name | quote }}
{{- else }}
      - {{ include "archetype.appname" $root }}.{{ include "archetype.clusterdns" $root }}
{{- end }}
{{- range $host.additionalhosts }}
      - {{ . }}
{{- end }}
{{- if $host.secretName }}
      secretName: {{ $host.secretName }}
{{- else }}
      secretName: {{ include "archetype.shortname" $root }}-cert
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end -}}
