{{- $root := . -}}
{{- $common := dict "Values" .Values.common -}}
{{- $noCommon := omit .Values "common" -}}
{{- $overrides := dict "Values" $noCommon -}}
{{- $noValues := omit . "Values" -}}
{{- with merge $noValues $overrides $common -}}
{{- $config := .Values.ingress -}}

{{- if and $config.enabled (eq $config.type "istio") }}
{{- if not ($config.gateway) }}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ include "common.shortname" $root }}-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - '*'
    port:
      name: http
      number: 80
      protocol: HTTP
{{- end }}

apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "common.shortname" $root }}-virtualservice
spec:
  gateways:
{{- if not ($config.istio.gateway) }}
  - {{ include "common.shortname" $root }}-gateway
{{- else }}
{{- with $config.istio.gateway }}
    {{ toYaml . | nindent 4 }}
{{- end }}
{{- end }}
  hosts:
{{- with $config.hosts }}
    {{ toYaml . | nindent 4 }}
{{- end }}
  http:
  - name: name: {{ include "common.shortname" $root }}-routes
    match:
    - uri:
        prefix: /
    route:
    - destination:
        host: kiali
        port:
          number: 20001
{{- end }}

{{- end -}}
