{{- $root := . -}}
{{- $common := dict "Values" .Values.common -}}
{{- $noCommon := omit .Values "common" -}}
{{- $overrides := dict "Values" $noCommon -}}
{{- $noValues := omit . "Values" -}}
{{- with merge $noValues $overrides $common -}}
{{- $ingress := .Values.ingress -}}

{{- if and $ingress.enabled (eq $ingress.type "istio") }}
{{- if not ($ingress.gateway) }}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ include "archetype.shortname" $root }}-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - '*'
    port:
      name: http
      number: 80
      protocol: HTTP
{{- else }}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  {{- if $ingress.gateway.name }}
  name: {{ $ingress.gateway.name }}
  {{- else }}
  name: {{ include "archetype.shortname" $root }}-gateway
  {{- end }}
spec:
  selector:
  {{- if $ingress.gateway.selectors }}
    {{- with $ingress.gateway.selectors }}
      {{ toYaml . | nindent 6 }}
    {{- end }}
  {{- else }}
    istio: ingressgateway
  {{- end }}
  servers:
  {{- if $ingress.gateway.servers }}
    {{- with $ingress.gateway.servers }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
  {{- else }}
    - hosts:
      - '*'
      port:
        name: http
        number: 80
        protocol: HTTP
{{- end }}

{{- range $host := $ingress.hosts }}
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
{{- if $host.name }}
  name: {{ $host.name }}
{{- else }}
  name: {{ include "archetype.shortname" $root }}-virtualservice
{{- end }}
spec:
  gateways:
  {{- if $ingress.gateways }}
    {{- with $ingress.gateways }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- else if $ingress.gateway.name }}
    - {{ $ingress.gateway.name }}
  {{- else }}
    - {{ include "archetype.shortname" $root }}-gateway
  {{- end }}
  hosts:
  {{- if $host.hostName }}
    - host: {{ $host.hostName | quote }}
  {{- else }}
    - host: "{{ include "archetype.appname" $root }}.{{ include "archetype.clusterdns" $root }}"
  {{- end -}}
  {{- range $host.additionalHosts }}
    - {{ . }}
  {{- end }}
  {{- if $host.config }}
    {{- $host.config | toYaml | nindent 2 }}
  {{- else }}
    {{- include "archetype.istio.virtualservice" $root | nindent 2 }}
  {{- end }}
{{- end }}
{{- end }}

{{- end -}}
