{{- $root := . -}}
{{- $ingress := .Values.ingress -}}
{{- $certIssuerMap := .Values.certIssuerMap -}}
{{- $zone := .Values.zone -}}
{{- if and $ingress.enabled ( eq $ingress.type "standard" ) }}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ include "archetype.shortname" $root }}
  annotations:
    {{- include "archetype.ingress.class" $root | nindent 4 }}
    {{- include "archetype.ingress.certissuer" (list $certIssuerMap $zone) | nindent 4 }}
  {{- if eq .Values.zone "internal" }}
    service.beta.kubernetes.io/{{ .Values.cloud | default "local" }}-load-balancer-internal: "true"
  {{- end }}
  {{- if $ingress.prometheusScraped }}
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ $ingress.prometheusPort | default .Values.ports.prometheus | quote }}
  {{- end }}
{{- if $ingress.rewrite }}
    ingress.kubernetes.io/rewrite-target: {{ $ingress.rewriteTarget | default "/" | quote }}
{{- end }}
  labels:
    ingressName: {{ include "archetype.shortname" $root }}
    dnsRoot: {{ .Values.dnsRoot }}
    {{- include "archetype.labels" $root | nindent 4 }}
  {{- with $ingress.labels }}
    {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
  {{- range $host := $ingress.hosts }}
  - http:
      paths:
      {{- if $host.paths }}
        {{- $host.paths | toYaml | nindent 8 }}
      {{- else }}
        {{- include "archetype.ingress.service" $root | nindent 8 }}
      {{- end }}
    {{- if not $host.skipHostName -}}
    {{- if $host.hostName }}
    host: {{ $host.hostName | quote }}
    {{- else if $host.name }}
    host: "{{ $host.name }}.{{ include "archetype.clusterdns" $root }}"
    {{- else }}
    host: "{{ include "archetype.appname" $root }}.{{ include "archetype.clusterdns" $root }}"
    {{- end }}
    {{- end }}
  {{- if or $ingress.tlsEnabled $host.secretName }}
  tls:
    - hosts:
      {{- if $host.hostName }}
      - {{ $host.hostName | quote }}
      {{- else if $host.name }}
      - "{{ $host.name }}.{{ include "archetype.clusterdns" $root }}"
      {{- else }}
      - "{{ include "archetype.appname" $root }}.{{ include "archetype.clusterdns" $root }}"
      {{- end }}
      {{- range $host.additionalhosts }}
      - {{ . }}
      {{- end }}
      {{- if $host.secretName }}
      secretName: {{ $host.secretName }}
      {{- else }}
      secretName: {{ include "archetype.shortname" $root }}-cert
      {{- end }}
  {{- end }}
  {{- end }}
{{- end -}}
