{{- $root := . -}}
{{- $gateway := .Values.istio.gateway -}}
{{- if $gateway.enabled }}
{{- if hasKey $gateway "config" }}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
{{- if hasKey $gateway "name" }}
  name: {{ $gateway.name }}
{{- else }}
  name: {{ include "archetype.shortname" $root }}-gateway
{{- end }}
spec:
  selector:
  {{- if hasKey $gateway "selectors" }}
    {{- with $gateway.selectors }}
      {{ toYaml . | nindent 6 }}
    {{- end }}
  {{- else }}
    istio: istiogateway
  {{- end }}
  servers:
  {{- if $gateway.config.servers }}
    {{- with $gateway.config.servers }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
  {{- else }}
    - hosts:
      - '*'
      port:
        name: http
        number: 80
        protocol: HTTP
  {{- end }}
{{- else }}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "archetype.shortname" $root }}-gateway
spec:
  selector:
    istio: istiogateway
  servers:
  - hosts:
    - '*'
    port:
      name: http
      number: 80
      protocol: HTTP
{{- end }}
{{- end -}}
