{{- $root := . -}}
{{- $ingress := .Values.ingress -}}
{{- $gateway := .Values.istio.gateway -}}

{{- if and $ingress.enabled (eq $ingress.type "istio") }}
{{- range $host := $ingress.hosts }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
{{- if $host.name }}
  name: {{ $host.name }}
{{- else }}
  name: {{ include "archetype.appname" $root }}-virtualservice
{{- end }}
  {{- include "archetype.namespace.name" $root | nindent 2 }}
spec:
  gateways:
  {{- if $ingress.gateways }}
    {{- with $ingress.gateways }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- else if hasKey $gateway "name" }}
    - {{ $gateway.name }}
  {{- else }}
    - {{ include "archetype.appname" $root }}-gateway
  {{- end }}
  hosts:
  {{- if $host.hostName }}
    - host: {{ $host.hostName | quote }}
  {{- else }}
    - host: "{{ include "archetype.appname" $root }}.{{ include "archetype.clusterdns" $root }}"
  {{- end }}
  {{- range $host.additionalHosts }}
    - {{ . }}
  {{- end }}
    http:
  {{- if $host.config }}
    {{- $host.config | toYaml | nindent 4 }}
  {{- else }}
    {{- include "archetype.istio.virtualservice" $root | nindent 4 }}
  {{- end }}
{{- end }}
{{- end -}}
