{{- $root := . -}}
{{- range $name, $job := .Values.jobs -}}
{{- if $job.enabled }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $name | replace "_" "-"  }}
  {{- with $job.annotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "archetype.labels" $root | nindent 4 }}
    {{- with $job.labels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
spec:
  activeDeadlineSeconds: {{ default 300 $job.activeDeadlineSeconds }}
  template:
    metadata:
      name: {{ include "archetype.shortname" $root }}-{{ $name | replace "_" "-"  }}
      labels:
        {{- include "archetype.labels" $root | nindent 8 }}
    spec:
      restartPolicy: '{{ default "Never" $job.restartPolicy }}'
      containers:
      - name: {{ $job.pod.name | default $name | replace "_" "-" }}
        image: {{ required "image.repository is required!" $root.Values.image.repository }}:{{ required "image.tag is required!" $root.Values.image.tag }}
        imagePullPolicy: {{ $root.Values.image.pullPolicy }}
        {{- with $job.pod.env }}
        env:
          {{ toYaml . | nindent 10 }}
        {{- end }}
        {{- if $root.Values.configMap.enabled }}
        envFrom:
          - configMapRef:
              name: {{ include "archetype.configmap.name" $root }}
          {{- if $root.Values.configMap.files }}
          - configMapRef:
              name: {{ include "archetype.configmap.name" $root }}-files
          {{- end }}
        {{- end }}
        {{- with $job.pod.command }}
        command:
          {{ toYaml . | nindent 10 }}
        {{- end }}
        {{- with $job.pod.args }}
        args:
          {{ toYaml . | nindent 10 }}
        {{- end }}
        {{- with $job.pod.securityContext }}
        securityContext:
          {{ toYaml . | nindent 10 }}
        {{- end }}
        volumeMounts:
        - mountPath: {{ $root.Values.persistence.mountPath | quote }}
          name: storage
        {{ include "archetype.files.volumeMounts" $root | nindent 8 }}
        {{- with $root.Values.resources }}
        resources:
        {{ toYaml . | nindent 10 }}
        {{- end }}
      imagePullSecrets:
      {{- if $root.Values.dockercfg.enabled }}
        - name: {{ include "archetype.fullname" $root }}
      {{- end }}
      {{- with $root.Values.image.pullSecrets }}
      {{- range . }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      volumes:
      - name: storage
      {{- if $root.Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ $root.Values.persistence.existingClaim | default (include "archetype.fullname" $root) }}
      {{- else }}
        emptyDir: {}
      {{- end }}
      {{ include "archetype.files.volumes" $root | nindent 6 }}
{{- end -}}
{{- end -}}
