{{- $root := . -}}
{{- range $name, $job := .Values.job -}}
{{- if $job.enabled }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "archetype.fullname" $root }}-{{ $name | replace "_" "-"  }}
{{- with $job.annotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
{{- end }}
  labels:
    {{- include "archetype.labels" $root | nindent 4 }}
{{- with $job.labels }}
{{ toYaml . | nindent 4 }}
{{- end }}
spec:
  activeDeadlineSeconds: {{ default 300 $job.activeDeadlineSeconds }}
  template:
    metadata:
      name: {{ include "archetype.fullname" $root }}-{{ $name | replace "_" "-"  }}
      labels:
        app: {{ include "common.name" $root }}
        release: {{ $root.Release.Name | quote }}
    spec:
      restartPolicy: '{{ default "Never" $job.restartPolicy }}'
      containers:
      - name: {{ include "common.name" $root }}
        image: {{ required "image.repository is required!" $root.Values.image.repository }}:{{ required "image.tag is required!" $root.Values.image.tag }}
        imagePullPolicy: {{ $root.Values.image.pullPolicy }}
        {{ include "archetype.common.env" $root | nindent 8 }}
        {{- if $job.pod.command }}
        command:
        {{ toYaml $job.pod.command | nindent 8}}
        {{- end }}
        args:
          {{ toYaml $job.pod.args | nindent 8 }}
        {{- with $job.pod.securityContext }}
        securityContext:
          {{ toYaml . | nindent 10 }}
        {{- end }}
        volumeMounts:
        - mountPath: {{ $root.Values.persistence.mountPath | quote }}
          name: storage
{{ include "archetype.files.volumeMounts" $root | indent 8 }}
{{- with $root.Values.resources }}
        resources:
{{ toYaml . | indent 10 }}
{{- end }}
      imagePullSecrets:
{{- if $root.Values.dockercfg.enabled }}
        - name: {{ include "archetype.fullname" $root }}
{{- end }}
{{- with $root.Values.image.pullSecrets }}
      {{- range . }}
        - name: {{ . }}
      {{- end }}
{{- end }}
      volumes:
      - name: storage
      {{- if $root.Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ $root.Values.persistence.existingClaim | default (include "archetype.fullname" $root) }}
      {{- else }}
        emptyDir: {}
      {{- end }}
{{ include "archetype.files.volumes" $root | indent 6 }}
{{- end -}}
{{- end -}}
