{{- $root := . -}}
{{- $common := dict "Values" .Values.common -}}
{{- $noCommon := omit .Values "common" -}}
{{- $overrides := dict "Values" $noCommon -}}
{{- $noValues := omit . "Values" -}}
{{- $keyvaultSecrets := .Values.keyvaultSecrets -}}
{{- $keyvaultName := .Values.keyvaultName -}}

{{- with merge $noValues $overrides $common -}}
{{- if $keyvaultSecrets.enabled }}
{{- range $secret := $keyvaultSecrets.secrets }}
---
apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  name: 'secret{{ $secret.secretKey | lower }}'
spec:
  vault:
    name: {{ $keyvaultName | lower }}
    object:
      type: '{{ $keyvaultSecrets.type }}'
      name: '{{ $secret.secretKey }}'
  output:
    secret:
      name: '{{ $secret.secretKey | lower }}'
      dataKey: '{{ $secret.secretKey }}'
{{- end }}
{{- end }}

{{- end -}}
