{{- $root := . -}}
{{- $namespace := .Values.namespace -}}
{{- if $namespace.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ if $namespace.name }}{{ $namespace.name }}{{ else }}{{ include "archetype.appname" $root }}{{ end }}
  labels:
    {{- include "archetype.labels" $root | nindent 4 }}
{{- with $namespace.labels }}
    {{ toYaml . | nindent 4 }}
{{- end }}
{{- with $namespace.annotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
{{- end }}
{{- end -}}