{{- $root := . -}}
{{- $config := .Values.namespace -}}
{{- if $config.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ if $config.name }}{{ $config.name }}{{ else }}{{ include "archetype.fullname" $root }}{{ end }}
  labels:
    {{- include "archetype.labels" $root | nindent 4 }}
{{- with $config.labels }}
    {{ toYaml . | nindent 4 }}
{{- end }}
{{- with $config.annotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
{{- end }}
{{- end -}}