{{- $root := . -}}
{{- $ports := .Values.ports -}}
{{- $service := .Values.service -}}

{{- if $service.enabled }}
{{- range $name, $portconfig := $service.ports }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "archetype.servicename" $root }}
{{- with $service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
  labels:
    {{- include "archetype.labels" $root | nindent 4 }}
spec:
  type: {{ $service.type }}
  {{- if $service.loadBalancerIP }}
  loadBalancerIP: {{ $service.loadBalancerIP }}
  {{- end }}
  ports:
  - name: {{ $name }}
    protocol: {{ $portconfig.protocol | default "TCP" }}
    port: {{ $portconfig.port | default $ports.external }}
    targetPort: {{ $portconfig.targetPort | default $ports.internal }}
  selector:
    {{- include "archetype.service.selectors" $root | nindent 4 }}
{{- end }}
{{- end -}}
