{{- $root := . -}}
{{- $common := dict "Values" .Values.common -}}
{{- $noCommon := omit .Values "common" -}}
{{- $overrides := dict "Values" $noCommon -}}
{{- $noValues := omit . "Values" -}}

{{- with merge $noValues $overrides $common -}}
{{- $ports := .Values.ports.defaults -}}
{{- $service := .Values.service -}}

{{- if $service.enabled }}
{{- range $name, $portconfig := $service.ports }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "archetype.fullname" $root }}-{{ $name }}
{{- with $service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
  labels:
    {{- include "archetype.labels" $root | nindent 4 }}
spec:
  type: {{ $service.type }}
  {{- if $service.loadBalancerIP }}
  loadBalancerIP: {{ $service.loadBalancerIP }}
  {{- end }}
  ports:
  - name: {{ $name }}
    protocol: {{ $portconfig.protocol | default "TCP" }}
    port: {{ $portconfig.port }}
    targetPort: {{ $portconfig.targetPort | default $ports.internal }}
  selector:
    {{- include "archetype.service.selectors" $root | nindent 4 }}
{{- end }}
{{- end }}
{{- end -}}
