{{- if .Values.statefulset -}}
{{- if .Values.statefulset.enabled -}}
kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
  name: {{ include "archetype.fullname" . }}
{{- with .Values.statefulset.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
{{ include "archetype.labels.standard" . | indent 4 }}
{{ include "archetype.labels" . | indent 4 }}
{{- with .Values.statefulset.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  selector:
    matchLabels:
      app: {{ include "common.name" . }}
      release: {{ .Release.Name }}
  serviceName: {{ include "archetype.fullname" . }}
  replicas: {{ .Values.replicaCount }}
{{- with .Values.statefulset.strategy }}
  updateStrategy:
{{ toYaml . | indent 4 }}
{{- end }}
  revisionHistoryLimit: {{ .Values.statefulset.revisionHistoryLimit }}
  template:
    metadata:
      name: {{ include "archetype.fullname" . }}
{{- with .Values.statefulset.pod.annotations }}
      annotations:
{{ toYaml . | indent 8 }}
{{- end }}
      labels:
        app: {{ include "common.name" . }}
        release: {{ .Release.Name | quote }}
        serve: "true"
{{- with .Values.statefulset.pod.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: {{ include "common.name" . }}
        image: {{ required "image.repository is required!" .Values.image.repository }}:{{ required "image.tag is required!" .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
{{ include "archetype.common.env" . | indent 8 }}
{{- with .Values.statefulset.pod.command }}
        command:
{{ toYaml . | indent 10 }}
{{- end }}
{{- with .Values.statefulset.pod.args }}
        args:
{{ toYaml . | indent 10 }}
{{- end }}
{{- with .Values.statefulset.pod.securityContext }}
        securityContext:
{{ toYaml . | indent 10 }}
{{- end }}
        ports:
{{- range $name, $port := .Values.service.ports }}
        - name: {{ $name }}
          containerPort: {{ $port.internal }}
          protocol: {{ default "TCP" $port.protocol  }}
{{- end }}
        volumeMounts:
        - mountPath: {{ .Values.statefulset.persistence.mountPath | quote }}
          name: {{ include "archetype.fullname" . }}
{{ include "archetype.files.volumeMounts" . | indent 8 }}
{{- with .Values.probes }}
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.resources }}
        resources:
{{ toYaml . | indent 10 }}
{{- end }}
      imagePullSecrets:
{{- if .Values.dockercfg.enabled }}
        - name: {{ include "archetype.fullname" . }}-dockercfg
{{- end }}
{{- with .Values.image.pullSecrets }}
      {{- range . }}
        - name: {{ . }}
      {{- end }}
{{- end }}
      volumes:
{{ include "archetype.files.volumes" . | indent 6 }}
{{- if not .Values.statefulset.persistence.useVolumeClaimTemplates }}
      - name: {{ (include "archetype.fullname" . ) }}
        persistentVolumeClaim:
          claimName: {{ .Values.statefulset.persistence.existingClaim | default (include "archetype.fullname" . ) }}
{{- end }}
{{- if .Values.statefulset.persistence.useVolumeClaimTemplates }}
  volumeClaimTemplates:
  - metadata:
      name: {{ include "archetype.fullname" . }}
{{- with .Values.statefulset.persistence.annotations }}
      annotations:
{{ toYaml . | indent 8 }}
{{- end }}
      labels:
{{ include "archetype.labels.standard" . | indent 8 }}
{{- with .Values.statefulset.persistence.labels }}
{{ toYaml . | indent 8 }}
{{- end }}
    spec:
      accessModes:
        - {{ .Values.statefulset.persistence.accessMode | quote }}
      resources:
        requests:
          storage: {{ .Values.statefulset.persistence.size | quote }}
{{- if .Values.statefulset.persistence.storageClass }}
{{- if (eq "-" .Values.statefulset.persistence.storageClass) }}
      storageClassName: ""
{{- else }}
      storageClassName: {{ .Values.statefulset.persistence.storageClass | quote }}
{{- end }}
{{- end }}
{{- end }}
{{- end -}}
{{- end -}}
